// ignore: non_constant_identifier_names
List<Map<String,dynamic>> LIST_DATA = [
  {
    "image" : "supercub.jpg",
    "title" : "Supercub",
    "status" : "ongoing",
    "synopsis" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "genre" : [
      "School",
      "Comedy",
      "Romance",
    ],
    "rating" : "8.6",
    "premiere" : "Spring 2020",
    "new-episode" : 12,
    "studio" : "HEHE Studio",
    "episode" : [
      "Episode 1",
      "Episode 2",
      "Episode 3",
      "Episode 4",
      "Episode 5",
    ],
  },
  {
    "image" : "naruto.jpg",
    "title" : "Naruto",
    "status" : "completed",
    "synopsis" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "genre" : [
      "Comedy",
      "Action",
      "Slice of Life"
    ],
    "rating" : "9.6",
    "premiere" : "Spring 1999",
    "new-episode" : 500,
    "studio" : "HEHE Studio",
    "episode" : [
      "Episode 1",
      "Episode 2",
      "Episode 3",
      "Episode 4",
      "Episode 5",
    ],
  },
  {
    "image" : "boruto.jpg",
    "title" : "Boruto",
    "status" : "ongoing",
    "synopsis" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "genre" : [
      "Comedy",
      "Action",
      "Slice of Life"
    ],
    "rating" : "6.6",
    "premiere" : "Autumn 2018",
    "new-episode" : 128,
    "studio" : "HEHE Studio",
    "episode" : [
      "Episode 1",
      "Episode 2",
      "Episode 3",
      "Episode 4",
      "Episode 5",
    ],
  },
  {
    "image" : "one-piece.jpg",
    "title" : "One Piece",
    "status" : "ongoing",
    "synopsis" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "genre" : [
      "Action",
      "Comedy",
      "Romance",
    ],
    "rating" : "9.6",
    "premiere" : "Spring 2001",
    "new-episode" : 976,
    "studio" : "HEHE Studio",
    "episode" : [
      "Episode 1",
      "Episode 2",
      "Episode 3",
      "Episode 4",
      "Episode 5",
    ],
  },
  {
    "image" : "demon-slayer.jpg",
    "title" : "Demon Slayer",
    "status" : "completed",
    "synopsis" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "genre" : [
      "Action",
      "Drama",
      "Comedy"
    ],
    "rating" : "8.6",
    "premiere" : "Fall 2019",
    "new-episode" : 12,
    "studio" : "HEHE Studio",
    "episode" : [
      "Episode 1",
      "Episode 2",
      "Episode 3",
      "Episode 4",
      "Episode 5",
    ],
  },
];